"use client";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Home",
	description: "Generated by create next app",
};

export default function Hello() {
	console.log("Hi I'm Client Component");

	return <div>Home</div>;
}
